CREATE DATABASE my_homy CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
USE my_homy;

CREATE TABLE cuenta(
nombreUsu VARCHAR(100) NOT NULL PRIMARY KEY,
correo VARCHAR(100) NOT NULL,
contrasenya VARCHAR(100) NOT NULL,
conectado TINYINT(1) NOT NULL,
validado TINYINT (1) NOT NULL,
codigo INT NOT NULL);

CREATE TABLE casa(
nombreCasa VARCHAR(100) NOT NULL PRIMARY KEY,
propietario VARCHAR(100),
FOREIGN KEY (propietario) REFERENCES cuenta(nombreUsu) ON DELETE CASCADE);

CREATE TABLE dispositivo(
nombreDispo VARCHAR(100) NOT NULL PRIMARY KEY,
encendido TINYINT(1) NOT NULL,
certificado VARCHAR (100) NOT NULL,
tipo VARCHAR (100) NOT NULL,
consumoBase DOUBLE NOT NULL,
precioBase DOUBLE NOT NULL,
estancia VARCHAR (100) NOT NULL,
nCasa VARCHAR(100),
FOREIGN KEY (nCasa) REFERENCES casa(nombreCasa) ON DELETE CASCADE);

CREATE TABLE resgistro(
idlog INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
dispo VARCHAR(100) NOT NULL,
estado TINYINT(1) NOT NULL,
fecha DATE NOT NULL,
tiempoUso TIME NOT NULL,
totalConsumo DOUBLE NOT NULL,
totalPrecio DOUBLE NOT NULL,
FOREIGN KEY (dispo) REFERENCES dispositivo(nombreDispo)ON DELETE CASCADE);