CREATE DATABASE myhomy CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
USE myhomy;

CREATE TABLE usuario(
id_usuario INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(100) NOT NULL,
apellido VARCHAR(100) NOT NULL,
correo VARCHAR(100) NOT NULL,
contrasenya VARCHAR(100) NOT NULL,
conectado TINYINT(1) NOT NULL
);

CREATE TABLE casa(
id_casa INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(100) NOT NULL,
fk_usuario INT NOT NULL,
FOREIGN KEY (fk_usuario) REFERENCES usuario(id_usuario)
);

CREATE TABLE estancia(
id_estancia INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(100) NOT NULL,
fk_casa INT NOT NULL,
FOREIGN KEY (fk_casa) REFERENCES casa(id_casa)
);

CREATE TABLE dispositivos(
id_dispositivos INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(100) NOT NULL,
encendido TINYINT(1) NOT NULL,
consumo_base INT NOT NULL,
tipo TINYINT NOT NULL,
func_espe TINYINT NOT NULL,
fk_estancia INT NOT NULL,
FOREIGN KEY (fk_estancia) REFERENCES estancia(id_estancia)
);