//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PiNaranja.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Idioma {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idioma() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PiNaranja.Resources.Idioma", typeof(Idioma).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Casa.
        /// </summary>
        internal static string btnActualizarCasa {
            get {
                return ResourceManager.GetString("btnActualizarCasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Dispositvo.
        /// </summary>
        internal static string btnAgregarDispositivo {
            get {
                return ResourceManager.GetString("btnAgregarDispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar .
        /// </summary>
        internal static string btnAgregarEstancia {
            get {
                return ResourceManager.GetString("btnAgregarEstancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Hogar.
        /// </summary>
        internal static string btnAgregarHogar {
            get {
                return ResourceManager.GetString("btnAgregarHogar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apagar.
        /// </summary>
        internal static string btnApagar {
            get {
                return ResourceManager.GetString("btnApagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consumo/Hora.
        /// </summary>
        internal static string btnCalculo {
            get {
                return ResourceManager.GetString("btnCalculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Contraseña.
        /// </summary>
        internal static string btnCambiarContraseña {
            get {
                return ResourceManager.GetString("btnCambiarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string btnCancelar {
            get {
                return ResourceManager.GetString("btnCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificar.
        /// </summary>
        internal static string btnCheckVCode {
            get {
                return ResourceManager.GetString("btnCheckVCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurar/Reanudar.
        /// </summary>
        internal static string btnConfigurar {
            get {
                return ResourceManager.GetString("btnConfigurar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Cuenta.
        /// </summary>
        internal static string btnCrearCuenta {
            get {
                return ResourceManager.GetString("btnCrearCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Casa.
        /// </summary>
        internal static string btnDeleteHome {
            get {
                return ResourceManager.GetString("btnDeleteHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detener.
        /// </summary>
        internal static string btnDetener {
            get {
                return ResourceManager.GetString("btnDetener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Dispositivo.
        /// </summary>
        internal static string btnEliminaDispositivo {
            get {
                return ResourceManager.GetString("btnEliminaDispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string btnEliminar {
            get {
                return ResourceManager.GetString("btnEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Cuenta.
        /// </summary>
        internal static string btnEliminarCuenta {
            get {
                return ResourceManager.GetString("btnEliminarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Estancia.
        /// </summary>
        internal static string btnEliminarEstancia {
            get {
                return ResourceManager.GetString("btnEliminarEstancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Hogar.
        /// </summary>
        internal static string btnEliminarHogar {
            get {
                return ResourceManager.GetString("btnEliminarHogar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encender.
        /// </summary>
        internal static string btnEncender {
            get {
                return ResourceManager.GetString("btnEncender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar Mail.
        /// </summary>
        internal static string btnEnviarMail {
            get {
                return ResourceManager.GetString("btnEnviarMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio Sesión.
        /// </summary>
        internal static string btnInicioSesion {
            get {
                return ResourceManager.GetString("btnInicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceso a Registros.
        /// </summary>
        internal static string btnLog {
            get {
                return ResourceManager.GetString("btnLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar.
        /// </summary>
        internal static string btnModificar {
            get {
                return ResourceManager.GetString("btnModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Dispositivo.
        /// </summary>
        internal static string btnMostrarDis {
            get {
                return ResourceManager.GetString("btnMostrarDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Dispositivo.
        /// </summary>
        internal static string btnMostrarModDis {
            get {
                return ResourceManager.GetString("btnMostrarModDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detener.
        /// </summary>
        internal static string btnParar {
            get {
                return ResourceManager.GetString("btnParar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperar Contraseña.
        /// </summary>
        internal static string btnRecuperarCon {
            get {
                return ResourceManager.GetString("btnRecuperarCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registros.
        /// </summary>
        internal static string btnRegistro {
            get {
                return ResourceManager.GetString("btnRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        internal static string btnReturn {
            get {
                return ResourceManager.GetString("btnReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Temporizador.
        /// </summary>
        internal static string btnTemporizador {
            get {
                return ResourceManager.GetString("btnTemporizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        internal static string btnVolver {
            get {
                return ResourceManager.GetString("btnVolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Panel de Crear Cuenta.
        /// </summary>
        internal static string FrmCrearCuenta {
            get {
                return ResourceManager.GetString("FrmCrearCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Panel de Inicio Sesión.
        /// </summary>
        internal static string FrmInicioSesion {
            get {
                return ResourceManager.GetString("FrmInicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Panel de Control.
        /// </summary>
        internal static string FrmPanelControl {
            get {
                return ResourceManager.GetString("FrmPanelControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Panel De Recuperar Cuenta.
        /// </summary>
        internal static string frmRecuperarCuenta {
            get {
                return ResourceManager.GetString("frmRecuperarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Panel De Reemplazar Casa.
        /// </summary>
        internal static string frmReemplazarCasa {
            get {
                return ResourceManager.GetString("frmReemplazarCasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Panel de Registros.
        /// </summary>
        internal static string frmRegistro {
            get {
                return ResourceManager.GetString("frmRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Panel de Verificación.
        /// </summary>
        internal static string FrmVerificacion {
            get {
                return ResourceManager.GetString("FrmVerificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dispositivos.
        /// </summary>
        internal static string grbAnyadirProducto {
            get {
                return ResourceManager.GetString("grbAnyadirProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de Contraseña.
        /// </summary>
        internal static string grbCambioCon {
            get {
                return ResourceManager.GetString("grbCambioCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añade una Estancia.
        /// </summary>
        internal static string grbCrearEstancia {
            get {
                return ResourceManager.GetString("grbCrearEstancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Hogar.
        /// </summary>
        internal static string grbCrearHogar {
            get {
                return ResourceManager.GetString("grbCrearHogar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Dispositivo.
        /// </summary>
        internal static string grbModificar {
            get {
                return ResourceManager.GetString("grbModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email de Recuperación.
        /// </summary>
        internal static string grbRecuperacion {
            get {
                return ResourceManager.GetString("grbRecuperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rellena los siguientes campos.
        /// </summary>
        internal static string grbRellena {
            get {
                return ResourceManager.GetString("grbRellena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Temporizadores.
        /// </summary>
        internal static string grbTemporizadores {
            get {
                return ResourceManager.GetString("grbTemporizadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        internal static string lblApellidos {
            get {
                return ResourceManager.GetString("lblApellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calculo.
        /// </summary>
        internal static string lblCalculo {
            get {
                return ResourceManager.GetString("lblCalculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificado: .
        /// </summary>
        internal static string lblCertificado2 {
            get {
                return ResourceManager.GetString("lblCertificado2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realiza click sobre la linea para seleccionar la Estancia o el Dispositivo.
        /// </summary>
        internal static string lblClick {
            get {
                return ResourceManager.GetString("lblClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Verificación.
        /// </summary>
        internal static string lblCode {
            get {
                return ResourceManager.GetString("lblCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code.
        /// </summary>
        internal static string lblCodigo {
            get {
                return ResourceManager.GetString("lblCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consumo Base.
        /// </summary>
        internal static string lblConsumoBase {
            get {
                return ResourceManager.GetString("lblConsumoBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string lblContraseña {
            get {
                return ResourceManager.GetString("lblContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string lblContrasenya {
            get {
                return ResourceManager.GetString("lblContrasenya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string lblCorreo {
            get {
                return ResourceManager.GetString("lblCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Nueva Cuenta myHomy.
        /// </summary>
        internal static string lblCrearCuenta {
            get {
                return ResourceManager.GetString("lblCrearCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Estancia.
        /// </summary>
        internal static string lblCrearEstancia {
            get {
                return ResourceManager.GetString("lblCrearEstancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        internal static string lblDireccion {
            get {
                return ResourceManager.GetString("lblDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dispositivo: .
        /// </summary>
        internal static string lblDispositivo {
            get {
                return ResourceManager.GetString("lblDispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dispositivos Registrados.
        /// </summary>
        internal static string lblDispositivosRegistrados {
            get {
                return ResourceManager.GetString("lblDispositivosRegistrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Estancia .
        /// </summary>
        internal static string lblEliminarEstancia {
            get {
                return ResourceManager.GetString("lblEliminarEstancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estancia.
        /// </summary>
        internal static string lblEstancia {
            get {
                return ResourceManager.GetString("lblEstancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estancia.
        /// </summary>
        internal static string lblEstanciaDispo {
            get {
                return ResourceManager.GetString("lblEstanciaDispo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estancias Registradas.
        /// </summary>
        internal static string lblEstanciasRegistradas {
            get {
                return ResourceManager.GetString("lblEstanciasRegistradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hogar.
        /// </summary>
        internal static string lblHogar {
            get {
                return ResourceManager.GetString("lblHogar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string lblIdioma {
            get {
                return ResourceManager.GetString("lblIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pulse sobre cualquier celda para modificar dispositivo, configurar temporizador, encenderlo y apagarlo..
        /// </summary>
        internal static string lblInfo {
            get {
                return ResourceManager.GetString("lblInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string lblNombre {
            get {
                return ResourceManager.GetString("lblNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string lblNombreDis {
            get {
                return ResourceManager.GetString("lblNombreDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del  Hogar.
        /// </summary>
        internal static string lblNombreHogar {
            get {
                return ResourceManager.GetString("lblNombreHogar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de la Nueva Casa.
        /// </summary>
        internal static string lblNuevaCasa {
            get {
                return ResourceManager.GetString("lblNuevaCasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Contraseña.
        /// </summary>
        internal static string lblNuevaCon {
            get {
                return ResourceManager.GetString("lblNuevaCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Panel de Control myHomy.
        /// </summary>
        internal static string lblPanelControl {
            get {
                return ResourceManager.GetString("lblPanelControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registros myHomy.
        /// </summary>
        internal static string lblRegistro {
            get {
                return ResourceManager.GetString("lblRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hogar.
        /// </summary>
        internal static string lblSelecHogar {
            get {
                return ResourceManager.GetString("lblSelecHogar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        internal static string lblTipo {
            get {
                return ResourceManager.GetString("lblTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Consumo:.
        /// </summary>
        internal static string lblTotalConsumo {
            get {
                return ResourceManager.GetString("lblTotalConsumo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string lblUsuario {
            get {
                return ResourceManager.GetString("lblUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vatios.
        /// </summary>
        internal static string lblW2 {
            get {
                return ResourceManager.GetString("lblW2", resourceCulture);
            }
        }
    }
}
